spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment-service
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        jdbc:
          time_zone: UTC
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: paymentConfirmation:com.jn.ecommerce.notification.PaymentNotificationRequest
        max.block.ms: 5000
        request.timeout.ms: 5000
        delivery.timeout.ms: 10000
        retries: 1
server:
  port: 8075