spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        jdbc:
            time_zone: UTC

  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    repair-on-migrate: true


server:
  port: 8052
