package com.jn.ecommerce.payment;

import org.springframework.stereotype.Service;

@Service
public class PaymentMapper {
    public Payment mapToPayment(PaymentRequest request) {
        return Payment.builder()
                // ID is generated by JPA
                .amount(request.amount())
                .paymentMethod(request.paymentMethod())
                .orderId(request.orderId())
                .build();
    }
}
