package com.jn.ecommerce.orderline;

import org.springframework.stereotype.Service;

import com.jn.ecommerce.order.Order;

@Service
public class OrderLineMapper {

    public OrderLine toEntity(OrderLineRequest orderLine) {

        return OrderLine.builder()
                // ID is generated by JPA; omit mapping from request
                .order(Order.builder().id(orderLine.orderId()).build())
                .productId(orderLine.productId())
                .quantity(orderLine.quantity())
                .build();
    }

    public OrderLineResponse toOrderLineResponse(OrderLine orderLine) {
        return new OrderLineResponse(
                orderLine.getId(),
                orderLine.getQuantity()
        );
    }

}
